---
title: "I swear that fire hydrant wasn't there (2 of 2)"
date: "January 18, 2018"
output:
 rmarkdown::html_document:
    theme: spacelab
---
This post is a continuation of the previous post except that I’ve visualized the 50 most ticketed parking locations within the city of Toronto for 2016. The figure and data below can be interacted with, if you’d like to determine what location generates the highest amount of ticket revenue for the city.

```{r, cache=TRUE, echo=FALSE}
library(ggplot2,warn.conflicts = FALSE);library(dplyr, warn.conflicts = FALSE);library(magrittr,warn.conflicts = FALSE);library(tmaptools,warn.conflicts = FALSE);
library(tmap,warn.conflicts = FALSE);library(ggmap,warn.conflicts = FALSE);library(DT,warn.conflicts = FALSE);library(leaflet);
Total_Fines_Locations<-read.csv("2018-01-10_Fine-locations-and-amounts.csv")
pal <- colorQuantile("YlOrRd", NULL, n = 8)
leaflet(data = filter(Total_Fines_Locations, location2!="2 JAMES ST")) %>%
  #addProviderTiles(providers$MtbMap) %>%
  #addProviderTiles(providers$Stamen.TonerLines,
  #                 options = providerTileOptions(opacity = 0.35)) %>%
  #addProviderTiles(providers$Stamen.TonerLabels) %>%
  addTiles( urlTemplate = "http://{s}.tiles.wmflabs.org/bw-mapnik/{z}/{x}/{y}.png") %>%
  addCircles(~lon, ~lat, 
                   radius=Total_Fines_Locations$total_fines/3000,
                  color=~pal(Total_Fines_Locations$total_fines),
                    opacity = .5  ,
                   popup = ~as.character(total_fines)) %>%
               addMarkers(~lon, ~lat, popup = ~as.character(Total_Fines_Locations$location2), 
                          label = ~as.character(Total_Fines_Locations$location2))




```
```{r, echo=FALSE}
library(dplyr, warn.conflicts = FALSE);library(magrittr,warn.conflicts = FALSE);library(tmaptools,warn.conflicts = FALSE);library(ggplot2,warn.conflicts = FALSE);
library(tmap,warn.conflicts = FALSE);library(ggmap,warn.conflicts = FALSE);library(DT,warn.conflicts = FALSE);library(leaflet)
datatable(select(Total_Fines_Locations,Year,location2,total_fines)
            ,colnames = c("Year","Location","Total Fines")) %>%
  formatCurrency(3,digits=0)

```

